### ISSUE TITLE
Make a page for direct download

### ISSUE THREAD

**Issue by ttodua** [KinoLien/gitzip#22]
Hi again.
It could have been nice, if on your site it was possible to automatically call, like this site does:

lets say, for : `https://github.com/golang/example/tree/master/template`:

https://download.runforgithub.com/golang/example/tree/master/template
or
https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/golang/example/tree/master/template

so, just opening that link, the folder download starts directly. 
If on your site, you could setup like that, it will be nice. (not complex page, without those access-token requests and etc, just very basic simple page, like there.)

If you could setup a page like that, then I will redirect the first link (i've developed that site) to your page, and in the future too, i'll use your site. I can also send the source-code of the first mentioned page, as it used minor PHP and HTACCESS parts, and probably that can be rewriten with JS too:   https://drive.google.com/open?id=1h8Cfj6x7J7_0rMXKV18mXm4TLHsJUjj6

**Comment by KinoLien** [comment]
I've done more than two years ago (issue: #5), and [here](https://github.com/KinoLien/gitzip/blob/gh-pages/README.md) is the instructions.

Try
https://kinolien.github.io/gitzip/?download=https://github.com/golang/example/tree/master/template

**Comment by ttodua** [comment]
the problem is that it doesn't work (at least for me). It doesnt start download, instead this page shows up: https://i.imgur.com/JyRp9H2.png  

ok, thanks anyway.

**Comment by KinoLien** [comment]
Sorry, I just didn't see the keyword that you want download via parameter without access token.

But the problem is you or your users have a chance to encounter the API rate limit; if over the limit, all API requests will be rejected by Github in few minutes, and then interrupt download progress.

So, for avoiding this problem, I added the logic `if and only if token exist, start download from url param` when I was designed the feature.

Anyway, I'v created an issue #23 for this.
